mean(BOD$Time)
mean (BOD$demand)
mean(BOD$demand)
median(BOD$Time)
median(BOD$demand)
min(BOD$Time)
min(BOD$demand)
max (BOD$Time)
max (BOD$demand)
quantile(BOD$Time, c(0.75))
quantile(BOD$demand,c(0.75))
quantile(BOD$Time)
quantile(BOD$demand)
var(BOD$Time)
var (BOD$demand)
sd(BOD$Time)
sd(BOD$demand)